### ISSUE TITLE
Complete suggestion's next word only (Alt+f in fish)

### ISSUE THREAD

**Issue by Ambrevar** [dieggsy/company-eshell-autosuggest#2]
Fish allows for completing with the following word from the suggestion by pressing `Alt+f` by default.

I don't know if company supports such a mechanism.  It would be great to have this in Eshell too.

**Comment by dieggsy** [comment]
I was thinking about that too, I'll look into it.

**Comment by dieggsy** [comment]
@Ambrevar I've added a kind of work around for this (I don't _think_ company has built-in support for such a mechanism, but I'd love to hear otherwise)

I tested briefly and it seemed to do the trick, let me know.
