### ISSUE TITLE
Doesn't work correctly with multiline eshell prompts

### ISSUE THREAD

**Issue by Fuco1** [dieggsy/company-eshell-autosuggest#6]
I have a multiline prompt, however the logic in `esh-autosuggest--prefix` doesn't work because the `lookint-at-p` triggers on the first line and there `eshell-bol` returns nil.

Is there any reason for this logic?  Woulnd't it be enough to only call `eshell-bol`?

**Comment by Fuco1** [comment]
I've fixed it by adding a search forward to skip to the end of the prompt

```elisp
(progn
                        (save-excursion
                          (beginning-of-line)
                          (while (not (looking-at-p eshell-prompt-regexp))
                            (forward-line -1))
                          (re-search-forward eshell-prompt-regexp nil t)
                          (eshell-bol)))
```

**Comment by dieggsy** [comment]
I think the reasoning here was just that 1) you only want suggestions when typing at a prompt in eshell, and 2) you need to be at the eshell prompt line for `(eshell-bol)` to actually return a number, which is what we use as the beginning position for the completion substring. Honestly, the `(while (not (looking-at ...` solution seems a bit silly and messy looking at it now, and `re-search-forward` seems like a much more robust and solid replacement.

**Comment by dieggsy** [comment]
@Fuco1 I don't have a mulitiline prompt, so I think I originally misunderstood your solution. Sorry for taking so long with this, but I've just pushed a commit that makes the fix exactly like your code here. Let me know if this works for you.

**Comment by okamsn** [comment]
I was having problems with this, and found that it was because `eshell-skip-prompt-function` was being given a buffer local value of `eshell-skip-prompt` in `eshell-prompt-initialize`, where the function `eshell-skip-prompt` seems to expect the prompt to be on only one line, given how it is used in `eshell-bol`.

For me, I've so far solved this resetting this value in `eshell-prompt-mode-hook`to something that moves the cursor back to the end of the prompt.

```el
(add-hook
 'eshell-prompt-mode-hook
 (lambda ()
   ;; Eshell resets this to a buffer-local value automatically.
   (setq-local eshell-skip-prompt-function (lambda () (goto-char (+ (point) 2))))))
```

**Comment by okamsn** [comment]
> I was having problems with this, and found that it was because `eshell-skip-prompt-function` was being given a buffer local value of `eshell-skip-prompt` in `eshell-prompt-initialize`, where the function `eshell-skip-prompt` seems to expect the prompt to be on only one line, given how it is used in `eshell-bol`.
> 
> For me, I've so far solved this resetting this value in `eshell-prompt-mode-hook`to something that moves the cursor back to the end of the prompt.
> 
> ```emacs-lisp
> (add-hook
>  'eshell-prompt-mode-hook
>  (lambda ()
>    ;; Eshell resets this to a buffer-local value automatically.
>    (setq-local eshell-skip-prompt-function (lambda () (goto-char (+ (point) 2))))))
> ```

After more testing, I've had better success just making `eshell-prompt-regexp` just match the last line of the prompt, which seems to also work better with other libraries.
